// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztcflzayubwitjpqqrtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0Y2ZsemF5dWJ3aXRqcHFxcnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODY1MTAsImV4cCI6MjA3MTY2MjUxMH0.9i1Vmc3tgLYVeHDj6FZS9Dwlx8oEyypJUTtU_AXhDE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});